### ISSUE TITLE
有关labelme

### ISSUE THREAD

**Issue by Pan-zhaoyu** [hitzoro/FCN-ColorLabel#1]
(labelme) robotics@robotics-MS-7A67:~/pan/test$ labelme_json_to_dataset _static/car.json
Traceback (most recent call last):
  File "/home/robotics/anaconda2/envs/labelme/bin/labelme_json_to_dataset", line 45, in <module>
    main()
  File "/home/robotics/anaconda2/envs/labelme/bin/labelme_json_to_dataset", line 23, in main
    os.mkdir(out_dir)
OSError: [Errno 2] No such file or directory: '_static/car_json'

上面是我的报错，由于博客登录不上去，如果您方便的话可以加一下您微信吗？有关数据集制作，我有一些问题想要咨询，WC; XiaoZhao31. 谢谢您！

**Comment by hitzoro** [comment]
你这个应该是路径问题吧，是不是多了个空格在写路径的时候 labelme_json_to_dataset _static/car.json 这个地方好好检查下，你看你这里dataset后和_static之间就多了一个空格

**Comment by Pan-zhaoyu** [comment]
您好，谢谢你，我找到一个办法解决了labelme_json_to_dataset <filename>.json，这个可以保存下来～

**Comment by Pan-zhaoyu** [comment]
您好，不好意思，我这边还有一个问题：检查转化后图片的格式时，总报错
NameError: name 'PIL' is not defined
我确定我电脑里有PIL，试过很多方法，一直报错，请问这是什么原因呢？
